### ISSUE TITLE
Redmine 5.0.0 Zeitwerks unhappy with redmine_reformat 

### ISSUE THREAD

**Issue by JDQuackers** [orchitech/redmine_reformat#13]
I just performed an upgrade of Redmine 4.2.2 to 5.0.0 and when attempting to start the Redmine application with this plugin in the plugins directory, Zeitwerks gets very angery, causing the application to crash:

```
[ E 2022-04-02 03:48:37.6520 2096/Ta age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 2-2] Cannot checkout session because a spawning error occurred. The identifier of the error is e8e4f981. Please see earlier logs for details about the error.
App 3943 output: Error: The application encountered the following error: cannot load such file -- redmine_reformat/converters/configured_converters (LoadError)
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
App 3943 output:     /home/redmine/redmine-5.0.0/plugins/redmine_reformat/lib/redmine_reformat/converters.rb:4:in `<top (required)>'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 3943 output:     /home/redmine/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
App 3943 output:     /home/redmine/redmine-5.0.0/config/environment.rb:16:in `<top (required)>'
App 3943 output:     config.ru:3:in `require'
App 3943 output:     config.ru:3:in `block in <main>'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 3943 output:     /home/redmine/.rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 3943 output:     config.ru:1:in `new'
App 3943 output:     config.ru:1:in `<main>'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 3943 output:     /usr/share/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 3943 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-04-02 03:48:47.9749 2096/T2b age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/redmine/redmine-latest: The application encountered the following error: cannot load such file -- redmine_reformat/converters/configured_converters (LoadError)
  Error ID: 1a0f5cca
  Error details saved to: /tmp/passenger-error-ef5CBD.html
```

This is my environment that works as long as I remove the `redmine_reformat` directory from plugins:

```
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   3.0.0-p0 (2020-12-25) [x86_64-linux]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  no plugin installed
```

As soon as I put the plugin into the plugins directory and restart, the application crashes again.

**Comment by njnatale-lm** [comment]
Redmine 5 has been released for a while now... are there any updates on updating this plugin to be compatible?

**Comment by njnatale-lm** [comment]
@martincizek are there any updates on this? Redmine 5 has been a publicly available release for months.

**Comment by benibr** [comment]
I'm also very interested in Redmine 5 support for the plugin. I tried to solve some problems myself and pushed the results to #14
