### ISSUE TITLE
Multithreading mode does not work

### ISSUE THREAD

**Issue by nedprofit** [orchitech/redmine_reformat#15]
When trying to use multithreading, example:  

`rake reformat:convert to_formatting=html RAILS_ENV=production workers=2
`

Log:
```
/home/nouara/projects/redmine-5.0.3/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:40:in `block (2 levels) in multi_run': uninitialized constant RedmineReformat::ReformatWorkerProgress (NameError)

          progress = RedmineReformat::ReformatWorkerProgress.new(progress_ipc)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/nouara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/fork_tracker.rb:10:in `block in fork'
        from /home/nouara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/fork_tracker.rb:8:in `fork'
        from /home/nouara/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7/lib/active_support/fork_tracker.rb:8:in `fork'
        from /home/nouara/projects/redmine-5.0.3/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:38:in `block in multi_run'
        from /home/nouara/projects/redmine-5.0.3/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:37:in `times'

```

Redmine: 5.0.3
Ruby: 3.1.2
DB: PostgreSQL14

**Comment by jirutka** [comment]
I’ve encountered the same error.

**Comment by martincizek** [comment]
I've also noticed there is a query issue when there are more workers than items to be processed, probably due to changed behaviour of newer Rails. Workers expected to process zero records were actually assigned with all records. Subsequently, a sanity check failed.

```
progress.rb:34:in `progress': Document: progress > subtotal (RuntimeError)
```
