### ISSUE TITLE
No converter found for Setting#welcome_text

### ISSUE THREAD

**Issue by naveedkamran** [orchitech/redmine_reformat#3]
We have Redmine 4.1.1.stable running in a docker contianer.

While converting Textile to Markdown, I am getting this error:

```
root@f38ec02f8812:/usr/src/redmine# rake reformat:convert to_formatting=markdown
W, [2021-05-04T12:16:29.018661 #2235]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2021-05-04T12:16:29.124150 #2235]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
W, [2021-05-04T12:16:29.138689 #2235]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2021-05-04T12:16:29.472389 #2235]  WARN -- : Creating scope :having_mail. Overwriting existing method User.having_mail.
W, [2021-05-04T12:16:31.720383 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.721348 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.721750 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.722163 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.722563 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.722955 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
W, [2021-05-04T12:16:31.723362 #2235]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:370)
Running with setup:
{:converters_json=>"(use default converters)",
 :to_formatting=>"markdown",
 :workers=>1,
 :dryrun=>false}
All 1/1 workers started.
Settings
rake aborted!
No converter found for Setting#welcome_text
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converters.rb:14:in `convert'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:241:in `convert'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:156:in `migrate_setting'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:144:in `block in migrate_settings'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:143:in `each'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:143:in `migrate_settings'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:130:in `do_migrate'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:118:in `block (3 levels) in call'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/context.rb:40:in `with_cached_projects'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:117:in `block (2 levels) in call'
/usr/src/redmine/app/models/mailer.rb:615:in `with_deliveries'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:116:in `block in call'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:115:in `call'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:110:in `call'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:36:in `convert_redmine'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:24:in `run'
/usr/src/redmine/plugins/redmine_reformat/lib/tasks/reformat.rake:13:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => reformat:convert
(See full trace by running task with --trace)
```

I confirm that in Administration -> General -> Welcome text there is no text and the field is empty.

**Comment by martincizek** [comment]
Can you please check that your text formatting settings is `textile` at the time you run the `redmine_reformat`?
* In GUI: Administration -> Settings -> Text formatting
* Command line: `echo 'Setting.text_formatting' | rails console` - it should say `"textile"`

> I confirm that in Administration -> General -> Welcome text there is no text and the field is empty.

This should not have any effect, it is just the first thing that is migrated. I admit that the error could have been reported in a less confusing way. :)

As you are using the default converter setup, the same error would be probably raised on any item. It means that it cannot pick conversion for your Redmine.

The default converter setup is as follows:
``` ruby
    DEFAULT_CONVERTER_CONFIG = [
      {
        from_formatting: 'textile',
        to_formatting: ['markdown', 'common_mark'],
        converters: 'TextileToMarkdown',
      }, {
        from_formatting: 'markdown',
        to_formatting: 'common_mark',
        converters: ['MarkdownToCommonmark'],
        force_crlf: false,
        match_trailing_nl: false,
      }, {
        to_formatting: 'html',
        converters: ['RedmineFormatter'],
      }
    ]
```

So if you changed the text formatting to markdown prior to migration (or if you run the migration again after a **successful** previous migration), it does not know how to convert markdown to markdown :-)

P.S.:
* The text_formatting is not changed if the migration fails, it is transaction-safe.
* You may consider using the new `common_mark` format (the format used in GitLab and GitHub). We maintain docker images for it until Redmine merges it to the core. It is better and safer: https://registry.hub.docker.com/r/orchitech/redmine-gfm
* I've added the `from_formatting` to the setup summary to make it more clear.

**Comment by martincizek** [comment]
Closing due to lack of feedback.

**Comment by thomasschuiki** [comment]
We are facing a similar problem. Can we exclude the Settings from the conversion somehow? I tried excluding it via "items" but that does nothing.

```
Docker Image: sameersbn/redmine:5.1
```
```
redmine_production=# select * from settings where name='text_formatting';
 id |      name       |  value  |         updated_on
----+-----------------+---------+----------------------------
 40 | text_formatting | textile | 2025-05-06 14:36:48.130137
(1 row)
```

```
redmine@d402d2b00b7a:~/redmine$ bundle exec rake reformat:convert to_formatting=common_mark converters_json='[{"items":["wiki_content_versions","settings"],"from_formatting": "textile","to_formatting": "common_mark","converters": null}]' --trace                                                                       ** Invoke reformat:convert (first_time)                                                                                                                                                                                                                                                                                     ** Invoke environment (first_time)                                                                                                                                                                                                                                                                                          ** Execute environment                                                                                                                                                                                                                                                                                                      ** Execute reformat:convert  
Running with setup:                                                                                                                                                                                                                                                                                                 [0/1857]
{:converters_json=>
  "[\n" +                                                                                                                                                                                                                                                                                                                     "  {\n" +
  "    \"items\": [\n" +
  "      \"wiki_content_versions\",\n" +
  "      \"settings\"\n" +
  "    ],\n" +
  "    \"from_formatting\": \"textile\",\n" +
  "    \"to_formatting\": \"common_mark\",\n" +
  "    \"converters\": null\n" +
  "  }\n" +
  "]",
 :to_formatting=>"common_mark",
 :workers=>1,
 :dryrun=>false,
 :from_formatting=>"(based on your Setting.text_formatting: textile)"}
All 1/1 workers started.
Settings
rake aborted!
No converter found for Setting#welcome_text
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converters.rb:14:in `convert'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:243:in `convert'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:158:in `migrate_setting'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:146:in `block in migrate_settings'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:145:in `each'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:145:in `migrate_settings'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:132:in `do_migrate'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:120:in `block (3 levels) in call'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/context.rb:40:in `with_cached_projects'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:119:in `block (2 levels) in call'
/home/redmine/redmine/app/models/mailer.rb:637:in `with_deliveries'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:118:in `block in call'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activerecord-6.1.7.10/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'                                                                                                                                                     /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activerecord-6.1.7.10/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'                                                                                                                                                  /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'                                                                                                                                                 /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'                                                                                                                                                                /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'                                                                                                                                                                /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activesupport-6.1.7.10/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activerecord-6.1.7.10/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activerecord-6.1.7.10/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'                                                                                                                                                              /home/redmine/data/tmp/bundle/ruby/3.2.0/gems/activerecord-6.1.7.10/lib/active_record/transactions.rb:209:in `transaction'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:117:in `call'                                                                                                                                                                                                                        /home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:112:in `call'                                                                                                                                                                                                                        /home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:31:in `convert_redmine'
/home/redmine/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:19:in `run'
/home/redmine/redmine/plugins/redmine_reformat/lib/tasks/reformat.rake:13:in `block (2 levels) in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:83:in `block in run'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:80:in `run'
/home/redmine/data/tmp/bundle/ruby/3.2.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/3.2.0/bin/rake:25:in `load'
/home/redmine/redmine/vendor/bundle/ruby/3.2.0/bin/rake:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli/exec.rb:59:in `load'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli/exec.rb:59:in `kernel_load'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli.rb:452:in `exec'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor.rb:538:in `dispatch'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.6.6/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.6.6/exe/bundle:28:in `block in <top (required)>'                                                                                                                                                                                                                                           /usr/local/bundle/gems/bundler-2.6.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.6.6/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => reformat:convert
```
