### ISSUE TITLE
RuntimeError for converting Textile to Markdown format

### ISSUE THREAD

**Issue by naveedkamran** [orchitech/redmine_reformat#7]
We have Redmine 4.1.1 running in a official docker container and have pandoc with following version:

> pandoc 2.2.1
> Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
> 

But it ends with following runtime error:

```
Traceback (most recent call last):
	64: from /usr/local/bundle/bin/rake:23:in `<main>'
	63: from /usr/local/bundle/bin/rake:23:in `load'
	62: from /usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
	61: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
	60: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
	59: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
	58: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
	57: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
	56: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
	55: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
	54: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
	53: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
	52: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
	51: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
	50: from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	49: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
	48: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
	47: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
	46: from /usr/local/bundle/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
	45: from /usr/src/redmine/plugins/redmine_reformat/lib/tasks/reformat.rake:13:in `block (2 levels) in <top (required)>'
	44: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:26:in `run'
	43: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:42:in `multi_run'
	42: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:42:in `collect'
	41: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:42:in `each'
	40: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:42:in `times'
	39: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:43:in `block in multi_run'
	38: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:43:in `fork'
	37: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:47:in `block (2 levels) in multi_run'
	36: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/invoker.rb:36:in `convert_redmine'
	35: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:110:in `call'
	34: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:115:in `call'
	33: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'
	32: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
	31: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
	30: from /usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	29: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
	28: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
	27: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:116:in `block in call'
	26: from /usr/src/redmine/app/models/mailer.rb:615:in `with_deliveries'
	25: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:117:in `block (2 levels) in call'
	24: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/context.rb:40:in `with_cached_projects'
	23: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:118:in `block (3 levels) in call'
	22: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:132:in `do_migrate'
	21: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:182:in `migrate_wiki_versions'
	20: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:69:in `find_each'
	19: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:135:in `find_in_batches'
	18: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `in_batches'
	17: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:222:in `loop'
	16: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:238:in `block in in_batches'
	15: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
	14: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block in find_each'
	13: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `each'
	12: from /usr/local/bundle/gems/activerecord-5.2.4.2/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
	11: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:188:in `block in migrate_wiki_versions'
	10: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/convert_redmine.rb:241:in `convert'
	 9: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converters.rb:11:in `convert'
	 8: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converters.rb:11:in `each'
	 7: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converters.rb:12:in `block in convert'
	 6: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/configured_converter.rb:39:in `convert'
	 5: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/converter_chain.rb:19:in `convert'
	 4: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/converter_chain.rb:19:in `each'
	 3: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/converter_chain.rb:20:in `block in convert'
	 2: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/textile_to_markdown/converter.rb:12:in `convert'
	 1: from /usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/textile_to_markdown/converter.rb:40:in `call'
/usr/src/redmine/plugins/redmine_reformat/lib/redmine_reformat/converters/textile_to_markdown/converter.rb:207:in `exec_pandoc_with_timeout': Persistent pandoc error occured, check pandoc version. Aborting. (pid 7916 exit 65) (RuntimeError)
```

**Comment by martincizek** [comment]
Please try to locate the input and try running pandoc on it manually. Also, try not to use parallel processing if you use it.
Based on the quoted output, it's not possible to say anything more than a pandoc conversion has timed out.

**Comment by martincizek** [comment]
Closing due to lack of feedback.
